name: Deploy to Firebase Hosting  # Имя workflow, отображается в разделе Actions GitHub

on:  # События, которые запускают workflow
  push:
    branches:
      - main  # Workflow запускается при пуше в ветку main
  pull_request:
    types: [closed]  # и при закрытии любого pull request

jobs:  # Задачи, которые выполняет workflow
  deploy:  # Имя задачи
    runs-on: ubuntu-latest  # Операционная система, на которой будет выполняться задача
    #if: github.event.pull_request.merged == true  # Условие: задача выполняется только если pull request был смержен
    steps:  # Шаги выполнения задачи
    - uses: actions/checkout@v2  # Шаг для проверки кода из репозитория

    - name: Setup Flutter  # Название шага
      uses: subosito/flutter-action@v1  # Использование действия для установки Flutter
      with:
        flutter-version: '3.16.5' # Указываем точную версию Flutter

    - name: Install dependencies  # Шаг для установки зависимостей
      run: flutter pub get  # Команда для установки зависимостей

    - name: Build web  # Шаг для сборки веб-версии приложения
      run: flutter build web  # Команда для сборки веб-приложения

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

    - name: Deploy to Firebase # Шаг для развёртывания на Firebase
      run: firebase deploy --only hosting --project miro-5e729